WARNING | 2023-03-03 13:02:09,546 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
DEBUG   | 2023-03-03 13:02:09,548 | arbiter.master_chief.sa_recon | Creating CFG
Identifying functions:   0%|          | 0/36 [00:00<?, ?it/s]INFO    | 2023-03-03 13:02:09,612 | arbiter.master_chief.sa_recon | Starting recon of 0x401000
INFO    | 2023-03-03 13:02:09,612 | arbiter.master_chief.sa_recon | Starting recon of 0x401020
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x40102d
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x401030
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x40103f
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x401040
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x40104f
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x401050
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x40105f
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x401060
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x401070
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x401080
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x401090
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x4010a0
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x4010ce
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x4010cf
INFO    | 2023-03-03 13:02:09,613 | arbiter.master_chief.sa_recon | Starting recon of 0x4010d0
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x4010f9
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401100
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401139
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401140
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401175
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401179
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401180
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401189
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401293
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x4012a0
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401305
INFO    | 2023-03-03 13:02:09,614 | arbiter.master_chief.sa_recon | Starting recon of 0x401310
INFO    | 2023-03-03 13:02:09,615 | arbiter.master_chief.sa_recon | Starting recon of 0x401318
INFO    | 2023-03-03 13:02:09,615 | arbiter.master_chief.sa_recon | Starting recon of 0x500000
INFO    | 2023-03-03 13:02:09,615 | arbiter.master_chief.sa_recon | Starting recon of 0x500008
INFO    | 2023-03-03 13:02:09,615 | arbiter.master_chief.sa_recon | Starting recon of 0x500010
INFO    | 2023-03-03 13:02:09,615 | arbiter.master_chief.sa_recon | Starting recon of 0x500018
INFO    | 2023-03-03 13:02:09,615 | arbiter.master_chief.sa_recon | Starting recon of 0x601050
INFO    | 2023-03-03 13:02:09,615 | arbiter.master_chief.sa_recon | Starting recon of 0x601058
Identifying functions: 100%|██████████| 36/36 [00:00<00:00, 12879.13it/s]
Traceback (most recent call last):
  File "vuln_templates/run_arbiter.py", line 125, in <module>
    main(template, target)
  File "vuln_templates/run_arbiter.py", line 53, in main
    sb = SA_Adv(sa, checkpoint=sources, require_dd=STRICT_MODE, call_depth=CALL_DEPTH, json_dir=JSON_DIR)
  File "/usr/local/lib/python3.8/dist-packages/arbiter-0.0.1-py3.8.egg/arbiter/master_chief/sa_advanced.py", line 47, in __init__
arbiter.utils.FatalError: No targets for SA advanced
